skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking_contract = "HEdU3KyTDRNCsq5gL1r576WC86rrx1bZFQ9e83iK6xig"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
